const SEND_GUESS_RANGE_REQUEST = "SEND_GUESS_RANGE_REQUEST"
const SEND_GUESS_RANGE_SUCCESS = "SEND_GUESS_RANGE_SUCCESS"
const SEND_GUESS_RANGE_FAILURE = "SEND_GUESS_RANGE_FAILURE"
const UPDATE_GUESS_VALUE = "UPDATE_GUESS_VALUE"
const CLOSE_GUESS_MESSAGE = "CLOSE_GUESS_MESSAGE"
const RESET_GUESSES = "RESET_GUESSES"

export {
  SEND_GUESS_RANGE_REQUEST,
  SEND_GUESS_RANGE_SUCCESS,
  SEND_GUESS_RANGE_FAILURE,
  UPDATE_GUESS_VALUE,
  CLOSE_GUESS_MESSAGE,
  RESET_GUESSES,
}
